spring.application.name=NormalizeService
#Port
server.port=${SEVER_PORT}
###Databases
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
###Flyway
spring.flyway.baselineOnMigrate=true
###ActiveMQ
spring.activemq.broker-url=${ACTIVE_MQ_HOST}
spring.activemq.user=${ACTIVE_MQ_USER}
spring.activemq.password=${ACTIVE_MQ_PASSWORD}
###Mybatis
mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
gradle.build.scan=false
#mybatis.type-aliases-package=com.api.NormalizeService.model







